apiVersion: v1
kind: Service
metadata:
  name: hebrew-date-converter
spec:
  type: NodePort  # Change the service type to NodePort
  ports:
    - port: 80    # Port on which the service will be exposed internally (ClusterIP)
      targetPort: 80  # Port on which your application is running inside the cluster
      nodePort: 30365  # Specify the node port (use a port number in the range 30000-32767)
  selector:
    app: hebrew-date-converter  # Match this selector to your deployment or pods
