apiVersion: v1
kind: Service
metadata:
  name: hebrew-date-converter
spec:
  selector:
    app: hebrew-date-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
